### ISSUE TITLE
I am getting error while run on emulator

### ISSUE THREAD

**Issue by Aeknasd145** [kashaf12/VOTE#1]
![image](https://user-images.githubusercontent.com/67686692/92313391-07baa880-efd4-11ea-8854-9ccf2cd98594.png)

**Comment by kashaf12** [comment]
Try this solution,

-update all files in app.gradle its asking for. - update all files in
build. gradle its asking for. - invalidate cache and restart Android
studio.

Aapt2 is enabled by default when you use android plugin for gradle 3.0. so
open gradle.properties and add android.enableAapt2=false as shown here
https://i.stack.imgur.com/lWyT2.png

**Comment by Aeknasd145** [comment]
file > project structure > dependencies > all modules > add dependency > library dependency > androidx.constraintlayout > latest version > ok > ok
error solved thank you
